### ISSUE TITLE
Back btn issue

### ISSUE THREAD

**Issue by Al-123654** [Al-123654/CrossPlatformApp2#1]
After logout, user is redirected to login screen. However, when back button is pressed at this point, the app goes back to user page.

**Comment by HamdyAli** [comment]
Fixed the issue by importing navigationOptions from react-navigation and adding it to RootStack in app.js

**Comment by HamdyAli** [comment]
Problem still persists on android with the android back button

**Comment by HamdyAli** [comment]
App can still go back on iOS when user slides his finger from left to right across the screen.

**Comment by HamdyAli** [comment]
On iOS gestures for moving back disabled problem still persists on android.

**Comment by Al-123654** [comment]
Add a way to go back to previous screens

**Comment by HamdyAli** [comment]
On Android user can still go back with the android back button

**Comment by Al-123654** [comment]
Found a way around the issue.

**Comment by Al-123654** [comment]
Solved
