### ISSUE TITLE
Image layout 

### ISSUE THREAD

**Issue by HamdyAli** [Al-123654/CrossPlatformApp2#26]
Image layout should be 3 across in a row and 6 in a column

**Comment by Al-123654** [comment]
Try to combine user images with followed images.

**Comment by Al-123654** [comment]
User images and followed images combined.

**Comment by Al-123654** [comment]
Refer to https://medium.com/code-well-live-forever/building-a-react-native-image-gallery-b8622e2b41fa

**Comment by Al-123654** [comment]
Done.
