### ISSUE TITLE
Limit number of comments per page

### ISSUE THREAD

**Issue by HamdyAli** [Al-123654/CrossPlatformApp2#40]
One page should display a maximum of 20 comments.

**Comment by Al-123654** [comment]
Comments limit mostly works as intended.

**Comment by Al-123654** [comment]
Add spinner on btn click.

**Comment by HamdyAli** [comment]
More comments btn no longer appears briefly on posting second comment onwards.

**Comment by HamdyAli** [comment]
After user posts a comment, comment display now shows a spinner to indicate loading
