### ISSUE TITLE
Images in feeds  load multiple times if clicked repeatedly

### ISSUE THREAD

**Issue by HamdyAli** [Al-123654/CrossPlatformApp2#43]
If this happens then clicking the back button just causes it to go back to the same screen. Same problem happens if profile button is clicked repeatedly

**Comment by HamdyAli** [comment]
Issue has been solved in feeds will solve for tabbed images

**Comment by Al-123654** [comment]
Solved in tabbed images

**Comment by Al-123654** [comment]
Solved.
