### ISSUE TITLE
Update explore js to include a search bar

### ISSUE THREAD

**Issue by Al-123654** [Al-123654/CrossPlatformApp2#48]
Searching for other users

**Comment by Al-123654** [comment]
Search bar included.

**Comment by Al-123654** [comment]
Searching users works.

**Comment by Al-123654** [comment]
Following still works

**Comment by Al-123654** [comment]
Add a little bit of styling

**Comment by Al-123654** [comment]
Search btn could be a bit clearer

**Comment by Al-123654** [comment]
Add a way to load list on enter/return

**Comment by HamdyAli** [comment]
List also loads when user presses enter on the keyboard by adding onSubmitEditing to TextInput
