### ISSUE TITLE
Registration validation

### ISSUE THREAD

**Issue by HamdyAli** [Al-123654/CrossPlatformApp2#9]
There is no validation for empty, correct email, password length and so on.

**Comment by Al-123654** [comment]
Username 5-10 chars, alphanumeric.
Password min 8 chars,
Fname lastname alphabets.

**Comment by Al-123654** [comment]
Try to move validation checks to only after btn is pressed

**Comment by Al-123654** [comment]
Moved validation to on press

**Comment by Al-123654** [comment]
Validation complete from the app side
